EW-626: Update personenkontext.
dBildungsplattform/dbildungs-iam-server pull request #103
Opened 2023-11-16 07:38 UTC by mkreuzkam-cap

# Description
Adds a PUT endpoint to update a personenkontext.

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/EW-626

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2023-11-17 10:42 UTC, psachmann requested changes

2023-11-17 10:42 UTC, psachmann commented on src/modules/person/api/personenkontext.uc.spec.ts
> +                personenkontextServiceMock.updatePersonenkontext.mockResolvedValue({
Missing blank line.

2023-11-17 13:29 UTC, mkreuzkam-cap commented on src/modules/person/api/person-api.mapper.profile.spec.ts
> +            ).not.toThrowError(MappingError);
Done

2023-11-17 13:29 UTC, mkreuzkam-cap commented on src/modules/person/api/person-api.mapper.profile.spec.ts
> +            ).not.toThrowError(MappingError);
Done

2023-11-17 13:29 UTC, mkreuzkam-cap commented on src/modules/person/domain/personenkontext.service.ts
> +        if (!storedPersonenkontext) {
Done

2023-11-17 13:29 UTC, mkreuzkam-cap commented on src/modules/person/domain/personenkontext.service.ts
> +            revision: string;
Done

2023-11-17 13:29 UTC, mkreuzkam-cap commented on src/modules/person/domain/personenkontext.service.ts
> +        if (!saved) {
Done

2023-11-17 13:29 UTC, mkreuzkam-cap commented on src/modules/person/api/personenkontext.uc.spec.ts
> +                personenkontextServiceMock.updatePersonenkontext.mockResolvedValue({
Done

2023-11-20 12:04 UTC, Fshmit approved these changes

2023-11-20 12:18 UTC, psachmann approved these changes

2023-11-20 12:18 UTC, psachmann commented on src/modules/person/domain/personenkontext.service.ts
> +        if (!saved) {
const updatedPersonenkontextDo: PersonenkontextDo<true> = Object.assign(storedPersonenkontext, newData);
        const saved: Option<PersonenkontextDo<true>> = await this.personenkontextRepo.save(updatedPersonenkontextDo);

        if (!saved) {
            return { ok: false, error: new EntityCouldNotBeUpdated('Personenkontext', updatedPersonenkontextDo.id) };
        }

        return { ok: true, value: saved };

2023-11-20 12:42 UTC, merged