EW-501 provided get all person
dBildungsplattform/dbildungs-iam-server pull request #12
Opened 2023-08-29 08:29 UTC by Fshmit

# Description
A get all persons endpoint was implemented. The request can be filtered with the following attributes: referrer, Familiennamen, Vorname, Sichtfeigabe.

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/EW-501

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-08-30 06:40 UTC, janrenz commented
I would add some pagination tests (or maybe I just overlooked them)

2023-08-30 07:46 UTC, Fshmit commented
> I would add some pagination tests (or maybe I just overlooked them)
pagination will be implemented and tested in a separate ticket that is still in the backlog.

2023-08-31 11:38 UTC, pkleybolte requested changes

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/persistence/person.repo.ts
> +            const result: Option<PersonDo<true>>[] = await this.em.find(PersonEntity, {
`em.find` should return `PersonEntity[]`. No Option and no DO. You won't need the filter in line 80 anymore.

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/persistence/person.repo.ts
> +    public async findAll(personDo: PersonDo<false>): Promise<Option<PersonDo<true>>[]> {
Option in the return Type does not make sense. The are no null or undefined entries in the array.

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/api/person.uc.ts
> +                if (person !== null && person !== undefined) {
null or undefined check can be removed after return type of service changed.

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/api/person.controller.spec.ts
> +    describe('when getting all persons', () => {
The description should just be 'findAll'.
We don't need a "when"-sentence for this.

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/api/person.uc.spec.ts
> +        describe('when person exists', () => {
when-describe not necessary

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/domain/person.service.spec.ts
> +        describe('when person exists', () => {
No when-describes necessary

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/domain/person.service.spec.ts
> +                expect(result).toBeInstanceOf(Array);
missing expected length of 0

2023-08-31 11:38 UTC, pkleybolte commented on src/modules/person/persistence/person.repo.integration-spec.ts
> +        describe('when persons were found', () => {
no when-describes necessary

2023-09-05 08:59 UTC, SimoneRadtke-Cap requested changes

2023-09-05 08:59 UTC, SimoneRadtke-Cap commented on src/modules/person/persistence/person.repo.integration-spec.ts
> +        it('should delete person from database', async () => {
'should find all persons from the database'

2023-09-05 08:59 UTC, SimoneRadtke-Cap commented on src/modules/person/persistence/person.repo.integration-spec.ts
> +            const personEntity1: PersonEntity = mapper.map(personDo1, PersonDo, PersonEntity);
You don't need personEntity1 and personEntity2. You can do
```
await em.persistAndFlush(mapper.map(personDo1, PersonDo, PersonEntity));
await em.persistAndFlush(mapper.map(personDo2, PersonDo, PersonEntity));
```

2023-09-05 08:59 UTC, SimoneRadtke-Cap commented on src/modules/person/persistence/person.repo.integration-spec.ts
> +            await expect(em.find(PersonEntity, {})).resolves.toHaveLength(2);
Why not 
```
expect(result).toHaveLength(2);
```
?

2023-09-05 08:59 UTC, SimoneRadtke-Cap commented on src/modules/person/persistence/person.repo.integration-spec.ts
> +        it('should return null', async () => {
Better 'should return an empty list'

2023-09-05 08:59 UTC, SimoneRadtke-Cap commented on src/modules/person/persistence/person.repo.integration-spec.ts
> +            await expect(em.find(PersonEntity, {})).resolves.toHaveLength(0);
Maybe better:
```
expect(result).toEqual([]);
```

2023-09-06 07:14 UTC, Fshmit commented on src/modules/person/api/person.controller.spec.ts
> +    describe('findAll', () => {
it is the new test structure without using when statements.

2023-09-06 07:21 UTC, Fshmit commented on src/modules/person/api/persons-query.param.spec.ts
> +describe('CreatePersonBodyParams', () => {
it is about the coverage :)

2023-09-06 09:01 UTC, Fshmit commented on src/modules/person/api/persons-query.param.spec.ts
> +describe('CreatePersonBodyParams', () => {
this file will be deleted. we don't need it even for the coverage

2023-09-07 12:30 UTC, closed without merging