Spsh 202 docker compose complete
dBildungsplattform/dbildungs-iam-server pull request #152
Opened 2023-12-06 15:02 UTC by kristoff-kiefer

# Description
Extend docker compose such that you can, if required run everything backend related in a compose.

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2023-12-07 07:54 UTC, marode-cap requested changes
Can't be used with the client, because the BFF tries to redirect the user to `http://keycloak:8080/*`when logging in. Since the browser is not a part of the docker network, this won't work.

Possible solution: 
Remove the custom dev-configs for docker and in the BFF service, replace
```yaml
ports:
  - 9091:9091
```
with
```yaml
network_mode: host
```
to switch the BFF service to host network resolution.
This way the BFF could still communicate with the other services using `localhost:port`.

Other solutions may be possible.

2023-12-07 07:54 UTC, marode-cap commented on compose.yaml
> +        type: bind
Consistent file ending
```suggestion
        type: bind
        
```

2023-12-07 07:54 UTC, marode-cap commented on docker-config/secrets.json
> +}
Consistent file ending
```suggestion
}

```

2023-12-14 08:39 UTC, marode-cap approved these changes

2023-12-20 09:11 UTC, DPDS93CT approved these changes

2023-12-20 09:23 UTC, merged