SPSH-385 Allows Adminuser Creation
dBildungsplattform/dbildungs-iam-server pull request #340
Opened 2024-03-01 13:18 UTC by casparneumann-cap

# Description
Adapted the person repository & aggregate to allow creating a person with fixed username & permanent password 

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-03-04 17:27 UTC, pkleybolte requested changes

2024-03-04 17:27 UTC, pkleybolte commented on src/modules/keycloak-administration/domain/keycloak-user.service.spec.ts
Wenn es nicht zu aufwändig ist, wäre es schön diese Fälle zu unterscheiden, obwohl es die Abdeckung nicht erhöht.
`service.setPassword(userId, generatedPassword);`, 
`service.setPassword(userId, generatedPassword, true);`, 
`service.setPassword(userId, generatedPassword, false);`

2024-03-04 17:27 UTC, pkleybolte commented on src/modules/person/persistence/person.repository.ts
> +                person.username ?? (await usernameGenerator.generateUsername(person.vorname, person.familienname));
Du hast insgesamt drei `?:`-Operatoren eingebaut und dabei Username und Passwort einzeln betrachtet. Fachlich gibt es eigentlich nur die Fälle, dass sowohl Username als auch Passwort oder keins davon angegeben werden. Nur eins davon sollte nicht passieren. Sauberer wäre ein  `if` statt der `?:`'s
Den theoretischen Fall nur eins von beiden anzugeben, könnte man hier oder direkt im Aggregate abfangen.

2024-03-05 08:49 UTC, casparneumann-cap commented on src/modules/person/persistence/person.repository.ts
> +                person.username ?? (await usernameGenerator.generateUsername(person.vorname, person.familienname));
Macht es aus fachlicher Sicht wirklich Sinn die Fälle saveUser mit fixem Benutzername und variablem Passwort / Mit variablem Benutzername / fixen Passwort auszuschließen?. Diese Fälle können eh nur direkt über das Aggregate getriggert werden für Seeding / Testing und werden nicht an die API exposed. Was ist mit dem Fall das man einen Benutzer mit fixem Benutzernamen anlegen möchte aber das Passwort nicht direkt festlegen will?

2024-03-05 09:07 UTC, casparneumann-cap commented on src/modules/keycloak-administration/domain/keycloak-user.service.spec.ts
Ist angepasst: aae1899baf0ab7aad4512b9bed268f8a4bc0037a

2024-03-05 15:19 UTC, casparneumann-cap commented on src/modules/person/persistence/person.repository.ts
> +                person.username ?? (await usernameGenerator.generateUsername(person.vorname, person.familienname));
Geklärt via Call

2024-03-05 16:42 UTC, pkleybolte requested changes

2024-03-05 16:42 UTC, pkleybolte commented on src/modules/person/api/person.controller.ts
> +        await this.personRepository.update(person, this.kcUserService);
Besser direkt im Repo injizieren. Der Keycloak gehört zur Persistenze. Das Modul sollte im API-Modul nicht importier werden.

2024-03-06 14:18 UTC, pkleybolte approved these changes

2024-03-18 08:14 UTC, casparneumann-cap commented on src/modules/person/api/person.controller.ts
> +        });
@kristoff-kiefer Das sieht für mich nicht richtig aus.

Das Objekt welches du an die createNew Methode gibst hat diese Struktur:
{
vorname:x,
familienname:x,
email:x,
referrer:x,
stammorganisation:x,
name:{
familienname:x,
vorname:x,
.....
},
....


Das erwatete PersonCreationParams-DTO der createNew Methode hat allerdigs eine ganz andere Struktur, welche nur top level props vorsieht. Oder habe ich hier einen Denkfehler?

2024-03-18 09:48 UTC, casparneumann-cap commented on src/modules/person/api/person.controller.ts
> +        });
In Call geklärt

2024-03-18 10:40 UTC, kristoff-kiefer approved these changes

2024-03-19 07:44 UTC, merged