Spsh 545, PersonPermissions per Inject
dBildungsplattform/dbildungs-iam-server pull request #432
Opened 2024-04-10 07:11 UTC by kristoff-kiefer

# Description

Provides a decorator which will inject PersonPermissions into a backend call if desired

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/SPSH-545

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-04-11 14:39 UTC, marode-cap approved these changes

2024-04-11 16:01 UTC, pkleybolte requested changes

2024-04-12 11:16 UTC, kristoff-kiefer commented on src/modules/authentication/passport/oidc.strategy.ts
> +                personPermissions: () => Promise.reject(),
Weil's zum Type gehört und gefüllt werden sollte

2024-04-12 11:18 UTC, kristoff-kiefer commented on src/modules/personenkontext/api/dbiam-personenkontext.controller.integration-spec.ts
> +        app = module.createNestApplication().enableShutdownHooks();
No that was an experiment, remnants of which seemed to have stuck

2024-04-12 11:21 UTC, pkleybolte commented on src/modules/authentication/api/permissions.decorator.ts
> +            return Promise.resolve(undefined);
Ja, wir haben drüber gesprochen. Meine Erinnerung: Ich habe gesagt, das `undefined` aus TS-Sicht ein valider Rückgabewert ist. Aber da man fachlich nichts mit undefined anfangen kann, weil der Nutzer dann keine Permissions hat, wollen wir direkt `rejecten`.

2024-04-12 11:21 UTC, kristoff-kiefer commented on jest.config.cjs
> +        "^.+\\.js$": "<rootDir>/../node_modules/babel-jest"
Make sure that the ts-to-js-mapping comes from a definite place. I hoped it would fix our testing issues

2024-04-12 15:35 UTC, pkleybolte approved these changes

2024-04-16 06:33 UTC, merged