SPSH-662: i18nKey in Responses für FE (teilweise-) einführen
dBildungsplattform/dbildungs-iam-server pull request #484
Opened 2024-05-06 12:14 UTC by DPDS93CT

# Description
Introduces i18nKey attribute in some responses to be used by FE. 
The more general SchulConnexError messages do not provide such a field.

## Links to Tickets or other pull requests
- https://github.com/dBildungsplattform/dbildungs-iam-server/pulls
- https://ticketsystem.dbildungscloud.de/browse/SPSH-662

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-05-07 14:47 UTC, pkleybolte requested changes
Zu viel Fachlichkeit in `/shared` und Abhängigkeiten von `/shared` auf die Fachmodule. 
Wir müssen den `schul-connex-error-mapper` grundsätzlich überdenken.

Vorschlag:
dbiam-rolle.error.ts (und ähnliche) kommen in das jeweilige Modul.
Jedes Modul definiert seinen eigenen ExceptionFilter, der die domain-errors in SchulConnex oder HttpExceptions transformiert.

Das Sahnehäubchen wäre, wenn die i18nKeys in der API nicht nur als `example` sondern als Type hinterlegt wären 
`i18nkey: 'NUR_LEHR_UND_LERN_AN_KLASSE' | 'GLEICHE_ROLLE_AN_KLASSE_WIE_SCHULE'`

2024-05-08 10:07 UTC, DPDS93CT commented on src/shared/error/schul-connex-error.mapper.ts
> +                i18nKey: 'SCHULE_UNTER_TRAEGER',
Ja, Konstanten werden nun per Enum in den entsprechenden Fehler-Klassen geführt und exportiert.

2024-05-15 09:27 UTC, pkleybolte approved these changes

2024-05-16 07:29 UTC, jaggarnaut commented on src/modules/rolle/api/dbiam-rolle.error.ts
> +    ADD_SYSTEM_RECHT_ERROR = 'ADD_SYSTEM_RECHT_ERROR',
```suggestion
    ROLLE_ERROR = 'ROLLE_SPECIFICATION_ERROR',
    ADD_SYSTEM_RECHT_ERROR = 'ADD_SYSTEMRECHT_ERROR',
```
Vorschlag für Einheitlichkeit

2024-05-16 08:22 UTC, DPDS93CT commented on src/modules/rolle/api/dbiam-rolle.error.ts
> +    ADD_SYSTEM_RECHT_ERROR = 'ADD_SYSTEM_RECHT_ERROR',
werde ich anpassen

2024-05-16 12:30 UTC, jaggarnaut commented on src/modules/organisation/api/organisation-exception-filter.ts
> +                i18nKey: OrganisationSpecificationErrorI18nTypes.KLASSEN_NAME_AN_SCHULE_EINDEUTIG,
```suggestion
                i18nKey: OrganisationSpecificationErrorI18nTypes.KLASSENNAME_AN_SCHULE_EINDEUTIG,
```

2024-05-17 08:54 UTC, jaggarnaut approved these changes

2024-05-24 05:40 UTC, merged