SPSH-616-benutzer-klasse-zuordnen
dBildungsplattform/dbildungs-iam-server pull request #488
Opened 2024-05-07 20:11 UTC by YoussefBouch

# Description

## Links to Tickets or other pull requests

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-05-13 10:16 UTC, DPDS93CT requested changes

2024-05-13 10:16 UTC, DPDS93CT commented on src/modules/organisation/persistence/organisation.scope.ts
Es scheint kein Unit- oder Integrationstest für diese Methode zu geben.

2024-05-14 08:24 UTC, YoussefBouch commented on src/modules/organisation/persistence/organisation.scope.ts
Done

2024-05-14 09:49 UTC, DPDS93CT approved these changes

2024-05-21 12:02 UTC, merged