Spsh 606
dBildungsplattform/dbildungs-iam-server pull request #507
Opened 2024-05-22 08:50 UTC by marode-cap

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-06-03 06:44 UTC, phaelcg approved these changes

2024-06-04 07:09 UTC, kristoff-kiefer requested changes

2024-06-04 07:09 UTC, kristoff-kiefer commented on src/modules/personenkontext/domain/personenkontext.ts
> +                'PersonenkontextAnlage invalid: role type does not match organistaion type',
typo

2024-06-04 08:22 UTC, marode-cap commented on src/modules/personenkontext/api/dbiam-personenkontext.controller.ts
> +        const saveResult: Result<Personenkontext<true>, DomainError> = await this.personenkontextRepo.createAuthorized(
renamed to `saveAuthorized`

2024-06-05 06:58 UTC, kristoff-kiefer approved these changes

2024-06-06 07:09 UTC, merged