SPSH-713: Test Coverage fixen
dBildungsplattform/dbildungs-iam-server pull request #514
Opened 2024-05-27 08:15 UTC by DPDS93CT

# Description
Change test coverage provider from v8 to babel, adjust tests.

## Links to Tickets or other pull requests

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-05-27 13:23 UTC, kristoff-kiefer requested changes
Bitte die Coverage-Anforderungen wieder hochziehen. So wie ich das sehe haben wir jetzt wieder 100%?

2024-05-27 13:29 UTC, marode-cap requested changes

2024-05-27 13:29 UTC, marode-cap commented on jest.config.cjs
> +            lines: 100, // ~99%
Remove the old comments

2024-05-27 13:29 UTC, marode-cap commented on src/modules/person/api/personen-query.param.ts
> -    @AutoMap(() => String)
Could remove all `@AutoMap` from this file, PersonenQueryParams is no longer used in any mappings

2024-05-27 13:29 UTC, marode-cap commented on src/modules/person/api/update-person.body.params.ts
> -    @AutoMap(() => String)
Same as PersonenQueryParams, not used by any auto-mappers

2024-05-28 07:34 UTC, marode-cap approved these changes

2024-05-28 07:39 UTC, kristoff-kiefer approved these changes

2024-05-28 07:39 UTC, merged