Spsh 641
dBildungsplattform/dbildungs-iam-server pull request #523
Opened 2024-05-30 11:41 UTC by Nael-Alshowaikh

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-05-31 10:53 UTC, DPDS93CT commented on compose.yaml
> +    external:
At least with Docker Compose V. 2.21 this configuration does not work, what version is used?

2024-06-03 05:47 UTC, DPDS93CT commented on otel-config.yaml
This may also be moved to /config folder. For the cluster I put it here /charts/dbildungs-iam-server/config/telemetry

2024-06-04 07:52 UTC, kristoff-kiefer requested changes
Move the otel config to config please

2024-06-04 07:57 UTC, kristoff-kiefer requested changes
Collection is done by SRE

2024-06-04 07:57 UTC, kristoff-kiefer commented on charts/dbildungs-iam-server/templates/telemetry-deployment.yaml
> +      containers:
I strongly doubt we need that. The collection should be done by SRE. Just providing the endpoints in the main app should be enough in the cluster. Just add a service that makes them publicly available

2024-06-04 11:41 UTC, DPDS93CT commented on otel-config.yaml
done

2024-10-11 09:51 UTC, closed without merging