Spsh 732: Person erstellen mit Rollenzuweisung zu einem Request bündeln
dBildungsplattform/dbildungs-iam-server pull request #542
Opened 2024-06-12 10:42 UTC by phaelcg

# Description
Implemented a new endpoint: POST/api/dbiam/personen 
Implemented all the checks for the Personenkontext in the PersonService

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/SPSH-732

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-06-18 16:43 UTC, YoussefBouch requested changes

2024-06-18 16:43 UTC, YoussefBouch commented on src/modules/personenkontext/specification/error/rolle-nur-an-passende-organisation.ts
> +            `Personenkontext could not be created/updates because it violates ${PersonenkontextSpecificationErrorI18nTypes.NUR_LEHR_UND_LERN_AN_KLASSE} specification`,
`updated`

2024-06-20 08:34 UTC, casparneumann-cap approved these changes
Fixed Migration (person_id_id) & Merge Problem (Compilation)

Insomnia Tests ✅

2024-06-20 11:00 UTC, YoussefBouch approved these changes

2024-06-20 11:41 UTC, merged