SPSH-746: E-Mailadresse für Lehrkräfte generieren
dBildungsplattform/dbildungs-iam-server pull request #549
Opened 2024-06-18 12:14 UTC by DPDS93CT

**PLEASE MERGE https://github.com/dBildungsplattform/dbildungs-iam-server/pull/589 BEFORE**

# Description
Provide Email aggregate, factory, service(s) and repository to provide functions:
- generate a new unique email address for a user
- disable and enable email account
- trigger enabling and creation of address if necessary, when user gets service-provider with EMAIL kategorie via rolle (PK)
- trigger disabling, when service-provider with EMAIL kategorie via rolle is removed from user (PK)

## Links to Tickets or other pull requests
- https://github.com/dBildungsplattform/dbildungs-iam-server/pulls
- https://ticketsystem.dbildungscloud.de/browse/SPSH-746

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-06-28 10:07 UTC, pkleybolte requested changes

2024-06-28 10:07 UTC, pkleybolte commented on src/modules/person/persistence/person.repository.ts
> +        const emailEntity: Option<EmailEntity> = await this.em.findOne(
EmailEntity -> EmailRepo

2024-06-28 10:07 UTC, pkleybolte commented on src/modules/person/domain/person.ts
> +    email?: string;
Warum brauche ich die Email in diesem Aggregate? Ich sehe nicht, wo das verwendet wird

2024-07-03 08:46 UTC, DPDS93CT commented on src/modules/person/persistence/person.repository.ts
> +        const emailEntity: Option<EmailEntity> = await this.em.findOne(
Kommentar zum Code hinzugefügt, dass dies hier geschieht um eine zirkuläre Abhängigkeit zu vermeiden.

2024-07-03 15:26 UTC, pkleybolte requested changes

2024-07-03 15:26 UTC, pkleybolte commented on src/modules/email/persistence/email.repo.spec.ts
> +    /*  function createEmailAddress(personId: PersonID): EmailAddress<false> {
Bitte auskommentierten Code entfernen.

2024-07-03 15:26 UTC, pkleybolte commented on src/modules/email/email.module.ts
> +    providers: [EmailRepo, EmailServiceRepo, EmailFactory, EmailGeneratorService, EmailEventHandler, EventService],
Statt `EventService` zu providen bitte das Modul importieren.

2024-07-03 15:26 UTC, pkleybolte commented on src/modules/person/domain/person.ts
> +        public email?: string,
Die wird nie gefüllt, oder? Dann besser weglassen.

2024-07-03 15:26 UTC, pkleybolte commented on src/modules/email/domain/email-event-handler.ts
> +    public async asyncPersonDeletedEventHandler(event: PersonDeletedEvent): Promise<void> {
"async" im Methodennamen ist nicht schön. Das erkennen wir schon am Return Type. -> handlePersonDeletedEvent

2024-07-03 15:26 UTC, pkleybolte commented on src/modules/email/domain/email.ts
> +        public readonly emailAddresses?: EmailAddress<boolean>[],
Warum ist das ein Array? Das scheint alles viel komplizierter zu machen.

2024-07-03 15:26 UTC, pkleybolte commented on src/modules/email/domain/email.ts
> +            this.emailAddresses[0].enabled = true;
Warum gerade die erste Adresse im Array? Sind die irgendwie sortiert?

2024-07-12 05:44 UTC, DPDS93CT commented on src/modules/person/domain/person.ts
> +        public email?: string,
Wird genutzt, um beim Löschen eines Nutzers das entsprechende Event mit email-address zu senden

2024-07-12 06:57 UTC, pkleybolte commented on src/modules/person/persistence/person.repository.ts
> +            person.email = await this.emailRepo.findEmailAddressByPerson(person.id);
Das können wir so nicht bauen. Das ist extrem ineffizient. Damit feuern wir hunderte Requests einzeln gegen die DB.
Wenn das Feld nur für das Löschen-Event verwendet wird, dann würde ich das weglassen. Beim Löschen kann ich an den Kontexten sehen, ob Email überhaupt betroffen ist.

´await` im Loop ist grundsätzlich schlecht und eigentlich sollt der Linter meckern. Die Regel haben wir anscheinend vergesen.

2024-07-12 09:42 UTC, pkleybolte requested changes

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/email/email.module.ts
> +    exports: [EmailRepo, EmailFactory, EmailEventHandler],
Werden die alle von anderen Modulen verwendet? Ich denke Factory und EventHandler können privat bleiben.

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/email/persistence/email.repo.ts
> +    public async findEmailAddressByPerson(personId: PersonID): Promise<string | undefined> {
Duplikat von findByPerson

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/email/domain/email.ts
> +export class Email {
Wozu braucht ich diese Klasse? Kann ich nicht direkt EmailAdress benutzen?

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.integration-spec.ts
> +                    provide: EmailRepo,
Warum wird das als einziges gemockt?

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/email/domain/email-event-handler.ts
> +                existingEmail.enable();
Das müsste noch persistiert werden, wenn die Adresse noch nicht enabled war.

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/email/domain/email-generator.ts
> +    public async generateAddress(firstname: string, lastname: string): Promise<Result<string>> {
Auf Basis des Namens erkenne ich nicht was der Unterschied zwischen `calculateAddress` und `generateAddress` ist. Ich schlage vor
`generateAddress` und `generateAvailableAdress`

2024-07-12 09:42 UTC, pkleybolte commented on src/modules/email/persistence/email.repo.ts
> +        const emailAddressEntity: Option<EmailAddressEntity> = await this.em.findOne(EmailAddressEntity, {
Kannst du hier mit der ID statt der Mailadresse suchen?

2024-07-17 09:58 UTC, DPDS93CT commented on src/modules/email/persistence/email.repo.ts
> +    public async findEmailAddressByPerson(personId: PersonID): Promise<string | undefined> {
Entfernt

2024-07-17 09:58 UTC, DPDS93CT commented on src/modules/email/domain/email.ts
> +export class Email {
Nun wird EmailAddress direkt verwendet

2024-07-18 15:45 UTC, pkleybolte requested changes

2024-07-18 15:45 UTC, pkleybolte commented on src/modules/email/domain/email-event-handler.ts
> +                const persistenceResult: EmailAddress<true> | DomainError = await this.emailRepo.save(existingEmail);
Falls die Adresse schon aktiviert war muss nicht persistiert werden.

2024-07-18 15:45 UTC, pkleybolte commented on src/modules/email/domain/email-event-handler.ts
> +                        `Successfully persisted email with new address:${persistenceResult.currentAddress}`,
Die ist nicht neu. Nur wieder aktiviert . Oder war schon aktiv. Das wird hier nicht unterschieden.

2024-07-18 15:45 UTC, pkleybolte commented on src/modules/person/person.module.ts
> +        EmailRepo,
Das wird schon im Email-Modul provided. Das darf hier nicht noch mal provided werden.

2024-07-18 15:45 UTC, pkleybolte commented on src/modules/person/api/personenuebersicht/dbiam-personuebersicht.controller.integration.spec.ts
> +                    provide: EmailRepo,
Wird vom Controller nicht benötigt

2024-07-19 13:29 UTC, pkleybolte approved these changes

2024-07-29 11:57 UTC, merged