Spsh 543: Client für Swagger mit längeren Timeouts
dBildungsplattform/dbildungs-iam-server pull request #572
Opened 2024-07-03 06:15 UTC by phaelcg

# Description
Added a test client for keycloak in the dev-realm-spsh.json.
Configured swagger to use the test client-id in the dev/test environment.
Updated the unit-tests for the Keycloak Configuration.

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/SPSH-543

## Changes

## Datasecurity
The test client should only be created in keycloak in the dev/test environment

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-07-04 08:55 UTC, marode-cap requested changes
This is supposed to help testers on the deployed branches, please make sure it works there.

2024-07-04 08:55 UTC, marode-cap commented on config/dev-realm-spsh.json
This file is only used for local environments I think? Needs to be included here as well:
https://github.com/dBildungsplattform/dbildungs-iam-keycloak/blob/main/charts/dbildungs-iam-keycloak/dev-realm-spsh.json

But this needs careful consideration, otherwise the new client will also be available in staging and production

2024-07-04 08:55 UTC, marode-cap commented on config/dev-realm-spsh.json
> +			"http://127.0,0.1:9090/*",
Second URI has a comma in it

2024-07-04 08:55 UTC, marode-cap commented on src/server/main.ts
> +                        : keycloakConfig.CLIENT_ID,
On the cluster both of these environment variables are set to "prod", even for our test-branches (Like the one for this PR).

2024-07-08 15:23 UTC, phaelcg commented on config/dev-realm-spsh.json
Exactly, the client cannot be deployed to stage or prod, that's why it needs to be clarified with dev-ops

2024-07-10 09:42 UTC, marode-cap approved these changes

2024-07-12 07:38 UTC, merged