SPSH-751: Email-Konto: Nutzer Umbenennung, deaktivieren, aktivieren
dBildungsplattform/dbildungs-iam-server pull request #599
Opened 2024-07-29 13:03 UTC by DPDS93CT

# Description
When vorname or familienname of person is changed e.g. via PUT /api/persob/PERSON_ID an PersonRenamedEvent is triggered and received in Email-Handler. Afterwards the old email-address is disabled and a new enabled one is created for the affected person.

## Links to Tickets or other pull requests
- https://github.com/dBildungsplattform/dbildungs-iam-server/pulls
- https://ticketsystem.dbildungscloud.de/browse/SPSH-751

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-08-01 10:35 UTC, kristoff-kiefer requested changes

2024-08-01 10:35 UTC, kristoff-kiefer commented on src/modules/person/persistence/person.repository.ts
> +        if (oldVorname !== newVorname) return true;
Only the first letter actually?

2024-08-01 11:40 UTC, DPDS93CT commented on src/modules/person/persistence/person.repository.ts
> +        if (oldVorname !== newVorname) return true;
adjusted

2024-08-02 08:16 UTC, kristoff-kiefer approved these changes

2024-08-08 10:50 UTC, merged