Spsh 840
dBildungsplattform/dbildungs-iam-server pull request #604
Opened 2024-08-06 14:50 UTC by tikle-cap

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-08-06 14:59 UTC, kristoff-kiefer requested changes

2024-08-06 14:59 UTC, kristoff-kiefer commented on src/modules/privacy-idea-administration/privacy-idea-administration.service.ts
> +    private tokenExpiry: number = 0;
Please add a unit to the variable name. What is it miliseconds? seconds? years?

2024-08-07 12:21 UTC, kristoff-kiefer approved these changes

2024-08-07 12:32 UTC, YoussefBouch requested changes
Der Endpunkt personen/{id} funktioniert nicht mehr? Kannst du drauf gucken bitte? Ich kann keine PersonDetails mehr sehen jetzt auf dem FE.

2024-08-13 09:57 UTC, YoussefBouch approved these changes

2024-08-13 09:59 UTC, merged