SPSH-842
dBildungsplattform/dbildungs-iam-server pull request #615
Opened 2024-08-14 09:41 UTC by DeFi3298

Backend Part for developing a TokenReset View for the TwoFactorAuthentification

[(https://ticketsystem.dbildungscloud.de/browse/SPSH-842)](https://ticketsystem.dbildungscloud.de/browse/SPSH-842)

2024-08-14 14:02 UTC, marode-cap requested changes

2024-08-16 15:01 UTC, DeFi3298 commented on src/modules/privacy-idea-administration/privacy-idea-administration.service.ts
> +        }
done

2024-08-16 15:01 UTC, DeFi3298 commented on src/modules/privacy-idea-administration/privacy-idea-administration.service.spec.ts
> +                mockJWTToken,
done

2024-08-16 15:01 UTC, DeFi3298 commented on src/modules/privacy-idea-administration/privacy-idea-administration.controller.ts
> +        return this.privacyIdeaAdministrationService.resetToken(userName);
done

2024-08-16 15:02 UTC, DeFi3298 commented on src/modules/privacy-idea-administration/privacy-idea-administration.controller.spec.ts
> +
done

2024-09-03 06:05 UTC, marode-cap approved these changes
Approved, but you should still check the three comments

2024-09-03 06:05 UTC, marode-cap commented on src/modules/privacy-idea-administration/privacy-idea-administration.service.ts
> +                throw new Error(`Error unassigning token: Unknown error occurred`);
Should these be generic Errors?

2024-09-12 15:49 UTC, merged