SPSH-1004
dBildungsplattform/dbildungs-iam-server pull request #639
Opened 2024-09-03 12:23 UTC by marode-cap

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-09-05 16:47 UTC, pkleybolte requested changes

2024-09-05 16:47 UTC, pkleybolte commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.ts
> -        this.eventService.publish(
Es sollte das PersonenkontextUpdatedEvent geworfen werden. Kein Event zu werfen ist keine Option.

2024-09-05 16:47 UTC, pkleybolte commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.ts
> -        this.eventService.publish(
Es sollte das PersonenkontextUpdatedEvent geworfen werden. Kein Event zu werfen ist keine Option.

2024-09-05 16:47 UTC, pkleybolte commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.ts
> -        this.eventService.publish(
Es sollte das PersonenkontextUpdatedEvent geworfen werden. Kein Event zu werfen ist keine Option.

2024-09-06 09:29 UTC, marode-cap commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.ts
> -        this.eventService.publish(
Deprecated

2024-09-06 09:29 UTC, marode-cap commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.ts
> -        this.eventService.publish(
Deprecated

2024-09-06 09:29 UTC, marode-cap commented on src/modules/personenkontext/persistence/dbiam-personenkontext.repo.ts
> -        this.eventService.publish(
Deprecated

2024-09-06 12:04 UTC, pkleybolte approved these changes

2024-09-09 06:30 UTC, merged