EW-641: Use German terminology in person module.
dBildungsplattform/dbildungs-iam-server pull request #64
Opened 2023-11-02 15:40 UTC by mkreuzkam-cap

# Description
Replaces English terminology with German to conform to DDD.
(includes the fields in the person entity)

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/EW-641

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2023-11-07 10:00 UTC, psachmann requested changes
- move create-person.dto.ts into the api folder
- cleanup the person-persistence.mapper.profile.ts

2023-11-07 10:01 UTC, psachmann reviewed
- move create-person.dto.ts into the api folder
- cleanup the person-persistence.mapper.profile.ts

2023-11-07 10:52 UTC, SimoneRadtke-Cap commented on src/modules/person/api/create-person.body.params.ts
Please change PersonBirthParams required to false and add the type to the ApiProperty

2023-11-07 11:09 UTC, SimoneRadtke-Cap commented on src/modules/person/domain/person.do.ts
> +    public namensPraefix?: string[];
I would prefer 'namePraefix' without 's' here for consistency.

2023-11-07 11:10 UTC, SimoneRadtke-Cap commented on src/modules/person/domain/person.do.ts
> +    public namensSuffix?: string[];
I would prefer 'nameSuffix' without 's' here for consistency.

2023-11-07 12:47 UTC, mkreuzkam-cap commented on src/modules/person/api/create-person.body.params.ts
Done

2023-11-07 12:48 UTC, mkreuzkam-cap commented on src/modules/person/api/person-name.params.ts
>      @ApiProperty({ name: 'titel', required: false })
Done

2023-11-07 12:48 UTC, mkreuzkam-cap commented on src/modules/person/persistence/person.entity.ts
> +    public namensSuffix?: string[];
Done

2023-11-07 12:48 UTC, mkreuzkam-cap commented on src/modules/person/api/create-person.body.params.ts
> +    @ApiProperty({ name: 'geschlecht', enum: Geschlecht, required: false })
Done

2023-11-07 12:56 UTC, SimoneRadtke-Cap commented on src/modules/person/api/person-name.params.ts
> +    @AutoMap(() => [String])
Can you add required false to the ApiProperty?

2023-11-07 14:56 UTC, SimoneRadtke-Cap approved these changes

2023-11-08 09:52 UTC, psachmann requested changes

2023-11-08 09:52 UTC, psachmann commented on src/modules/person/api/create-person.body.params.ts
>      @AutoMap()
Type is missing in the AutoMap decorator.

2023-11-08 09:52 UTC, psachmann commented on src/modules/person/api/create-person.body.params.ts
>      @AutoMap()
Type is missing in the AutoMap dcorator.

2023-11-08 09:52 UTC, psachmann commented on src/modules/person/api/person-api.mapper.profile.spec.ts
> +            expect(() => sut.map(personenkontextDo, PersonenkontextDo, CreatedPersonenkontextDto)).not.toThrowError(
Missing blank lines for better readabilty.

2023-11-08 09:52 UTC, psachmann commented on src/modules/person/api/person-birth.params.ts
Line 7: Type is missing in the AutoMap decorator.

2023-11-08 09:52 UTC, psachmann commented on src/modules/person/api/person.response.ts
>      @AutoMap()
Type is missing in the AutoMap decorator.

2023-11-08 10:40 UTC, merged