Fix Seeding Befristung
dBildungsplattform/dbildungs-iam-server pull request #651
Opened 2024-09-11 09:35 UTC by casparneumann-cap

# Description
Fix des Seeding-Bugs durch setzen einer statischen Befristung für all Personenkontexte bei der die Rolle das Merkmal BEFRISTUNG hat

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/SPSH-1053

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-09-11 15:29 UTC, pkleybolte requested changes

2024-09-11 15:29 UTC, pkleybolte commented on src/console/dbseed/domain/db-seed.service.ts
> +            console.log(referencedRolle.merkmale);
Bitte logger statt console.log

2024-09-11 17:43 UTC, YoussefBouch commented
Ich habe 2 Anmerkungen: 

Wie wird die Befristung das Problem mit den fehlenden ServiceProviders lösen? 





**2. Tatsächliches Verhalten (Fehlerbeschreibung): Länder haben fälschlicherweise Dienststellennummern

Im Schulportal SH werden die drei Länder (Land Schleswig-Holstein, Öffentliche Schulen Land Schleswig Holstein und Ersatzschulen Land Schleswig-Holstein) mit einer Dienststellennummer angezeigt, obwohl sie keine haben sollten. Bitte entfernen. Dies betrifft wohl auch Klassen.**

Wurde das hier auch mitgefixed?

2024-09-12 06:40 UTC, casparneumann-cap commented on src/console/dbseed/domain/db-seed.service.ts
> +            console.log(referencedRolle.merkmale);
Das waren nur remote debugging Kommentare die ich vergessen habe zu entfernen.

2024-09-12 06:45 UTC, casparneumann-cap commented
> Ich habe 2 Fragen:
> 
> **Wie wird die Befristung das Problem mit den fehlenden ServiceProviders lösen? Die Befristung in der DB sollte den Wert "Undefined" normalerweise akzeptieren, weil der technically als "Unbefristet" gilt.**
> 
> _Aus dem Ticket: Im Schulportal SH werden die drei Länder (Land Schleswig-Holstein, Öffentliche Schulen Land Schleswig Holstein und Ersatzschulen Land Schleswig-Holstein) mit einer Dienststellennummer angezeigt, obwohl sie keine haben sollten. Bitte entfernen. Dies betrifft wohl auch Klassen_
> 
> **Wurde das hier auch mitgefixed?**

Die Datenbank hat hier keinen NOT NULL Constraint und würde dementsprechend null/undefined akzeptieren. Unser Backend prüft allerdings zu recht, dass ein Kontext zu einer Rolle die eine Befristung verlangt auch explizit eine Befristung angibt. Deshalb müsssen wir das im Seeding berücksichtigen. 

Zu dem Thema "Aus dem Ticket: Im Schulportal SH werden die drei Länder (Land Schleswig-Holstein, Öffentliche Schulen Land Schleswig Holstein und Ersatzschulen Land Schleswig-Holstein) mit einer Dienststellennummer angezeigt, obwohl sie keine haben sollten. Bitte entfernen. Dies betrifft wohl auch Klassen" --> Nein das ist nicht Teil dieses Tickets

2024-09-12 07:22 UTC, YoussefBouch approved these changes

2024-09-12 07:37 UTC, pkleybolte commented on src/console/dbseed/domain/db-seed.service.ts
> +/* eslint-disable no-console */
Das bitte auch noch entfernen.

2024-09-12 08:10 UTC, pkleybolte approved these changes

2024-09-12 11:15 UTC, merged