SPSH-1137
dBildungsplattform/dbildungs-iam-server pull request #750
Opened 2024-11-13 08:08 UTC by he-meyer

# Description

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/SPSH-1137

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-11-14 12:23 UTC, tikle-cap commented on src/modules/cron/cron.controller.ts
> +                SchulConnexErrorMapper.mapDomainErrorToSchulConnexError(new CronJobError('Ungenügende Berechtigungen')),
ich würde wahrscheinlich eher MissingPermissionsError mit einer englischen Fehlermeldung verwenden

2024-11-14 12:32 UTC, tikle-cap commented on src/modules/service-provider/domain/service-provider.service.ts
> +        const vidisKeycloakGroup: string = 'VIDIS-service';
soll das so hard coded sein?

2024-11-14 12:39 UTC, tikle-cap commented on src/modules/service-provider/domain/service-provider.service.ts
> +                        'ffb411f6-8287-4939-b87d-13b6a4e7fdfa', // This is a random UUID
Wofür ist die ID?

2024-11-14 13:06 UTC, DeFi3298 commented on src/modules/cron/cron.controller.ts
> +                SchulConnexErrorMapper.mapDomainErrorToSchulConnexError(new CronJobError('Ungenügende Berechtigungen')),
@he-meyer siehe person.controller.ts
![image](https://github.com/user-attachments/assets/6ff98c39-4840-4691-a91a-2a13748b27bd)

2024-11-14 14:05 UTC, DeFi3298 requested changes

2024-11-15 07:38 UTC, tikle-cap approved these changes

2024-11-15 09:31 UTC, DeFi3298 approved these changes

2024-11-21 10:02 UTC, YoussefBouch commented on src/modules/service-provider/domain/service-provider.service.ts
> +                        const school: Result<
```suggestion
                        const orga: Result<
```

2024-11-25 09:01 UTC, YoussefBouch requested changes

2024-11-25 09:01 UTC, YoussefBouch commented on src/modules/service-provider/domain/service-provider.service.ts
> +                    this.logger.info(`ServiceProvider for VIDIS Angebot '${serviceProvider.name}' already exists.`);
Why do we need to construct the service provider when it already exists in the DB?

2024-11-25 13:04 UTC, YoussefBouch approved these changes

2024-11-29 10:28 UTC, merged