SPSH-1288
dBildungsplattform/dbildungs-iam-server pull request #774
Opened 2024-11-21 08:14 UTC by he-meyer

# Description

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/SPSH-1288

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2024-11-22 09:45 UTC, tikle-cap commented on src/modules/organisation/domain/organisation.service.ts
> +                            `Admin ${permissions.personFields.familienname} (${permissions.personFields.id}) hat versucht eine neue Klasse ${organisation.name} (${schoolName}) anzulegen. Fehler: ${er
ist familienname richtig? ich würde einfach den username nehmen

2024-11-25 12:34 UTC, DeFi3298 requested changes

2024-11-25 12:34 UTC, DeFi3298 commented on src/modules/organisation/persistence/organisation.repository.integration-spec.ts
> +                });
Siehe oben

2024-11-25 12:34 UTC, DeFi3298 commented on src/modules/organisation/persistence/organisation.repository.integration-spec.ts
> +        });
Siehe oben.

2024-11-25 12:34 UTC, DeFi3298 commented on src/modules/organisation/persistence/organisation.repository.ts
> +        if (permissions)
Siehe oben

2024-11-25 12:34 UTC, DeFi3298 commented on src/modules/rolle/api/rolle.controller.integration-spec.ts
> +        });
Siehe oben

2024-11-25 12:34 UTC, DeFi3298 commented on src/modules/rolle/api/rolle.controller.spec.ts
> +            });
Siehe oben

2024-11-25 12:34 UTC, DeFi3298 commented on src/modules/rolle/api/rolle.controller.ts
> +    }
Ein Benutzer kann mehrere Organisationen und Rollen haben, bzw. eine Person kann mehrere Personenkontexte haben. Ich glaube der Mehrwert ist hier nicht gegeben, sich den ersten Index des Arrays für die Rollen anzuschauen.

2024-11-26 14:44 UTC, DeFi3298 requested changes

2024-11-26 14:45 UTC, DeFi3298 approved these changes

2024-12-20 08:26 UTC, YoussefBouch approved these changes

2024-12-20 14:38 UTC, merged