Spsh 1327
dBildungsplattform/dbildungs-iam-server pull request #832
Opened 2024-12-09 14:21 UTC by tikle-cap

https://ticketsystem.dbildungscloud.de/browse/SPSH-1327

2024-12-11 08:52 UTC, he-meyer approved these changes

2024-12-11 12:37 UTC, marode-cap requested changes

2024-12-11 12:37 UTC, marode-cap commented on src/modules/authentication/api/person-time-limit-info.reponse.ts
> +    }
Are these nullable? They can't be undefined in the constructor (and the nullish operator in line 13 is unused)

2024-12-11 12:37 UTC, marode-cap commented on src/modules/authentication/authentication-api.module.ts
>      ],
Don't provide services from other modules, import the other module

2024-12-11 12:37 UTC, marode-cap commented on src/modules/person/domain/person-time-limit-info.service.ts
> +                await this.dBiamPersonenkontextService.getKopersPersonenkontext(person.id);
`isPersonalnummerRequiredForAnyPersonenkontextForPerson` and `getKopersPersonenkontext` do basically the same thing, can we consolidate these two so we save a DB query?

2024-12-12 13:28 UTC, marode-cap approved these changes

2024-12-16 19:06 UTC, merged