Spsh-1654: Paginierung des Importergebnis
dBildungsplattform/dbildungs-iam-server pull request #859
Opened 2024-12-20 14:19 UTC by phaelcg

# Description
- Paginierung des Importergebnis mit Limit & Offset
- Neuer Endpunkt GET/api/import/importedUsers? für die Abfrage des Importergebnis als JSON
- Refactoring des Import-Workflows
- Anpassung der Logs für die Importstatus
- Fix für den Import
- Unit- & Integrationtests

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/SPSH-1654

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2025-01-07 12:34 UTC, YoussefBouch commented
#844

2025-01-13 09:08 UTC, marode-cap requested changes

2025-01-13 09:08 UTC, marode-cap commented on src/modules/import/domain/import-workflow.ts
> +        this.initialize(importVorgang.organisationId!, importVorgang.rolleId!);
Also null-assertions here, to me this looks like the underlying data-structure might need a rework.
If these fields can actually be undefined, there should probably be a check for it

2025-01-13 09:08 UTC, marode-cap commented on src/modules/import/domain/import-workflow.ts
> +        if (numberOfRows > this.CSV_MAX_NUMBER_OF_USERS) {
Why the divide by 2?

2025-01-13 10:12 UTC, YoussefBouch commented on src/modules/import/domain/import-workflow.ts
> +        this.initialize(importVorgang.organisationId!, importVorgang.rolleId!);
There is apparently a check for it in the same file:

![image](https://github.com/user-attachments/assets/8a7dadd2-a153-4928-b164-8d22bd361610)

2025-01-13 10:12 UTC, YoussefBouch commented on src/modules/import/api/imported-user.response.ts
> +        this.status = importedDataItem.status!;
I changed the status to be always present but things like benutzername (referrer) or startpasswort come from another object definition and it could indeed be undefined according to typescript... just won't happen in a real life scenario..

2025-01-13 10:22 UTC, marode-cap commented on src/modules/import/domain/import-workflow.ts
> +        if (numberOfRows > this.CSV_MAX_NUMBER_OF_USERS) {
Ah, I missed that the regex contained a character group. We could switch the regex to `/(\n|\r\n)/g` which should encompass all the different line-endings used by Unix/Windows

2025-01-13 10:41 UTC, marode-cap commented on src/modules/import/domain/import-workflow.ts
> +        this.initialize(importVorgang.organisationId!, importVorgang.rolleId!);
Ah, but because it is at a different location TS can't infer the asserted type. Could you at least add a comment when using null-assertions, so the reader of the code knows where the check is?

2025-01-13 10:50 UTC, YoussefBouch commented on src/modules/import/domain/import-workflow.ts
> +        this.initialize(importVorgang.organisationId!, importVorgang.rolleId!);
done

2025-01-13 10:59 UTC, pkleybolte commented on src/modules/import/domain/import-workflow.ts
> +        if (numberOfRows > this.CSV_MAX_NUMBER_OF_USERS) {
I don't see a reason to divide by 2. There should be one occurence of \r\n per line.

2025-01-13 10:59 UTC, YoussefBouch commented on src/modules/import/domain/import-workflow.ts
> +        if (numberOfRows > this.CSV_MAX_NUMBER_OF_USERS) {
I used: `(/\r?\n/g)` it should look for \n everytime and an \r optionally

2025-01-13 11:01 UTC, pkleybolte commented on src/modules/import/domain/import-workflow.ts
> +        this.initialize(importVorgang.organisationId!, importVorgang.rolleId!);
Same file, but not the same method. It is not likely, but they could be null here.

2025-01-13 11:12 UTC, YoussefBouch commented on src/modules/import/domain/import-workflow.ts
> +        if (numberOfRows > this.CSV_MAX_NUMBER_OF_USERS) {
> I don't see a reason to divide by 2. There should be one occurence of \r\n per line.

Right but the \r and \n are counted here individually and so they give apparently double the correct number of rows. The new (/\r?\n/g) should solve it

2025-01-14 07:44 UTC, marode-cap commented
Tests are still failing

2025-01-28 00:22 UTC, merged